# Generated by Django 5.2.3 on 2025-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacant',
            old_name='title',
            new_name='house_title',
        ),
        migrations.AddField(
            model_name='vacant',
            name='rent_fee',
            field=models.CharField(default='Amount paid for the rent', max_length=100),
        ),
    ]
